[global]
dataFrameSerialization = "legacy"

[server]
headless = true
port = 8501
enableCORS = false

[browser]
gatherUsageStats = false
showErrorDetails = true

[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"