apiVersion: v1
kind: Service
metadata:
  name: azure-day2-engine-frontend-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-day2-engine.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "azure-day2-engine.selectorLabels" . | nindent 4 }}
    component: frontend