apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-day2-engine.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.global.azure.clientId | b64enc }}
  tenant-id: {{ .Values.global.azure.tenantId | b64enc }}
  client-secret: {{ .Values.global.azure.clientSecret | b64enc }}
  subscription-id: {{ .Values.global.azure.subscriptionId | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-day2-engine.labels" . | nindent 4 }}
type: Opaque
data:
  auth-secret-key: {{ .Values.global.auth.secretKey | b64enc }}
  admin-username: {{ .Values.global.auth.adminUsername | b64enc }}
  admin-password: {{ .Values.global.auth.adminPassword | b64enc }}